version: '2.1'

services: 
  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment:
      NC_PUBLIC_URL: ${NC_PUBLIC_URL:-http://localhost}
      NC_DB: "mysql2://${DB_HOST:-root_db}:3306?u=${DB_USER:-root}&p=${DB_PASSWORD:-password}&d=${DB_NAME:-nocodb}"
      NC_ADMIN_EMAIL: ${NC_ADMIN_EMAIL:-admin@example.com}
      NC_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD:-admin@example.com}
      NC_INVITE_ONLY_SIGNUP: ${NC_INVITE_ONLY_SIGNUP:-1} # https://github.com/nocodb/nocodb/issues/7814
      NC_DISABLE_TELE: ${NC_DISABLE_TELE:-1}
    image: "nocodb/nocodb:latest"
    ports: 
      - "${NOCODB_PORT:-80}:8080"
    restart: always
    volumes: 
      - "${DATA_DIR:-./data}/nocodb:/usr/app/data"
  
  root_db: 
    environment: 
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MARIADB_DATABASE: ${DB_NAME:-nocodb}
    image: mariadb:latest
    restart: always
    healthcheck: #https://mariadb.org/mariadb-server-docker-official-images-healthcheck-without-mysqladmin/
        test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
        start_period: 1m
        start_interval: 10s
        interval: 1m
        timeout: 5s
        retries: 3
    volumes: 
      - "${DATA_DIR:-./data}/mysql:/var/lib/mysql"
  
  phpmyadmin:
    depends_on:
      - root_db
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    environment:
      PMA_HOST: ${DB_HOST:-root_db}
      # PMA_USER: ${DB_USER:-root}
      # PMA_PASSWORD: ${DB_PASSWORD:-password}
      PMA_ABSOLUTE_URI: ${PMA_PUBLIC_URL:-http://localhost:8080}
    restart: always
  
  php-webserver:
    build: ./php
    ports:
      - "${SQL_EDITOR_PORT:-8081}:80"
    volumes:
      - ./admin:/var/www/html
    depends_on:
      - root_db
    environment:
      MYSQL_HOST: ${DB_HOST:-root_db}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_NAME:-nocodb}
      BASE_PATH: ${PHP_BASE_PATH:-/}
    restart: always