version: '3.8'

services:
  # Traefik Reverse Proxy
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment:
      NC_PUBLIC_URL: ${NC_PUBLIC_URL:-http://localhost}
      NC_DB: "mysql2://${DB_HOST:-root_db}:3306?u=${DB_USER:-root}&p=${DB_PASSWORD:-password}&d=${DB_NAME:-nocodb}"
      NC_ADMIN_EMAIL: ${NC_ADMIN_EMAIL:-admin@example.com}
      NC_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD:-admin@example.com}
      NC_INVITE_ONLY_SIGNUP: ${NC_INVITE_ONLY_SIGNUP:-1}  # https://github.com/nocodb/nocodb/issues/7814
      NC_DISABLE_TELE: ${NC_DISABLE_TELE:-1}
    image: "nocodb/nocodb:latest"
    restart: always
    volumes: 
      - "${DATA_DIR:-./data}/nocodb:/usr/app/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nocodb.rule=Host(`localhost`) || PathPrefix(`/`)"
      - "traefik.http.routers.nocodb.priority=1"
      - "traefik.http.services.nocodb.loadbalancer.server.port=8080"
  
  root_db: 
    environment: 
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MARIADB_DATABASE: ${DB_NAME:-nocodb}
    image: mariadb:latest
    restart: always
    healthcheck: #https://mariadb.org/mariadb-server-docker-official-images-healthcheck-without-mysqladmin/
        test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
        start_period: 1m
        start_interval: 10s
        interval: 1m
        timeout: 5s
        retries: 3
    volumes: 
      - "${DATA_DIR:-./data}/mysql:/var/lib/mysql"
  
  phpmyadmin:
    depends_on:
      - root_db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST:-root_db}
      PMA_ABSOLUTE_URI: ${NC_PUBLIC_URL:-http://localhost}/phpmyadmin
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=PathPrefix(`/phpmyadmin`)"
      - "traefik.http.routers.phpmyadmin.priority=10"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.middlewares.phpmyadmin-stripprefix.stripprefix.prefixes=/phpmyadmin"
      - "traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-stripprefix"
  
  sql-editor:
    build: ./php
    volumes:
      - ./admin:/var/www/html
    depends_on:
      - root_db
    environment:
      MYSQL_HOST: ${DB_HOST:-root_db}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_NAME:-nocodb}
      BASE_PATH: /sql
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sql-editor.rule=PathPrefix(`/sql`)"
      - "traefik.http.routers.sql-editor.priority=10"
      - "traefik.http.services.sql-editor.loadbalancer.server.port=80"
      - "traefik.http.middlewares.sql-editor-stripprefix.stripprefix.prefixes=/sql"
      - "traefik.http.routers.sql-editor.middlewares=sql-editor-stripprefix"

networks:
  default:
    name: nocodb-network